// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUqC3awgZrQfqlUtpMy9iyCyYTSIQLkDk',
    appId: '1:578924896526:web:37f5e60899ff843087375f',
    messagingSenderId: '578924896526',
    projectId: 'event-manager-92d8e',
    authDomain: 'event-manager-92d8e.firebaseapp.com',
    storageBucket: 'event-manager-92d8e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlQjxsqt1uHh6oiPaGzYVXM3U2YAv2wuM',
    appId: '1:578924896526:android:5f0e63e11e02bc4287375f',
    messagingSenderId: '578924896526',
    projectId: 'event-manager-92d8e',
    storageBucket: 'event-manager-92d8e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC308gPv_dZO50z9YC63ncUwWovVCcAgq8',
    appId: '1:578924896526:ios:d6c7b58de95920ef87375f',
    messagingSenderId: '578924896526',
    projectId: 'event-manager-92d8e',
    storageBucket: 'event-manager-92d8e.firebasestorage.app',
    iosBundleId: 'com.example.projectFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC308gPv_dZO50z9YC63ncUwWovVCcAgq8',
    appId: '1:578924896526:ios:d6c7b58de95920ef87375f',
    messagingSenderId: '578924896526',
    projectId: 'event-manager-92d8e',
    storageBucket: 'event-manager-92d8e.firebasestorage.app',
    iosBundleId: 'com.example.projectFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAUqC3awgZrQfqlUtpMy9iyCyYTSIQLkDk',
    appId: '1:578924896526:web:f3075270aeb2eb8287375f',
    messagingSenderId: '578924896526',
    projectId: 'event-manager-92d8e',
    authDomain: 'event-manager-92d8e.firebaseapp.com',
    storageBucket: 'event-manager-92d8e.firebasestorage.app',
  );
}
